name: Print Environment Variables

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  print-env-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variables
        run: |
          echo "Run ID: $GITHUB_RUN_ID"
          echo "Workflow: $GITHUB_WORKFLOW"
          echo "Action: $GITHUB_ACTION"
          echo "Actor: $GITHUB_ACTOR"
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Event Name: $GITHUB_EVENT_NAME"
          echo "Event Path: $GITHUB_EVENT_PATH"
          echo "Workspace: $GITHUB_WORKSPACE"
          echo "SHA: $GITHUB_SHA"
          echo "Ref: $GITHUB_REF"
          echo "Head Ref: $GITHUB_HEAD_REF"
          echo "Base Ref: $GITHUB_BASE_REF"
          echo "Server URL: $GITHUB_SERVER_URL"
          echo "API URL: $GITHUB_API_URL"
          echo "GraphQL URL: $GITHUB_GRAPHQL_URL"
