name: Simple Workflow

on: [push]

jobs:
  build:
    runs-on: Abc
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo "Hello, neww-orld!"

      - name: Display runner information
        run: uname -a
        
      - name: Check current user
        run: whoami
