name: Simple Workflow

on: [push]

jobs:
  build:
    runs-on: Abc
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo "Hello, neww-orld!"

      - name: Display runner information
        run: uname -a
        
      - name: Check current user
        run: whoami

      - name: Print checkout workspace path
        run: |
           echo "Checkout workspace path: $GITHUB_WORKSPACE"
           cd $GITHUB_WORKSPACE
           ls
           echo "checking varibules"
           echo "Custom variable USERNAME:${{ vars.USERNAME }}"
           echo "Custom variable DB:${{ vars.DB_PASSWORD }}"
           echo "checking secrtes"
           echo "Custom variable for SECRETS USERNAME:${{ secrets.ABC }}"
           mkdir -p /root/Automation_script
           cp -rf /$GITHUB_WORKSPACE* /root/Automation_script/
           DAYOFWEEK=$(date +"%A")
           if [ "$DAYOFWEEK" != "Friday" ]; then
           echo "Today is Tuseday"
           else
           echo "Its Friday"
           fi
          
           

