name: Simple Workflow

on: [push]

jobs:
  deployment_main:
    runs-on: Abc
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy application
        run: echo "Deploying application..."

  build:
    needs: [deployment_main]
    runs-on: Abc
    env:
      CI_DEBUG_TRACE: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo "Hello, neww-orld!"

      - name: Display runner information
        run: uname -a
        
      - name: Check current user
        run: whoami
