name: Sequential Jobs Example

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  stage1:
    runs-on: [self-hosted, phani]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Stage 1 - Print Message
        run: |
          echo "This is Stage 1"
          # Add other commands for Stage 1 here

  stage2:
    runs-on: [self-hosted, phani]
    needs: stage1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Stage 2 - Print Message
        run: |
          echo "This is Stage 2"
          # Add other commands for Stage 2 here
